version: '3.8'

services:
  # Servicio para la aplicación web Spring Boot
  web:
    build: .  # Le dice a Docker que busque un "Dockerfile" en esta carpeta
    ports:
      - "8080:8080" # Mapea el puerto de tu app al de tu Mac
    environment:
      # --- ¡LA LÍNEA CLAVE! ---
      # Activa el perfil "dev" para que Spring use el archivo application-dev.properties
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - db # Le dice a tu app que espere a que la base de datos esté lista

  # Servicio para la base de datos MongoDB
  db:
    image: mongo:latest
    ports:
      # Mapea el puerto 27017 para que puedas conectarte con Compass
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      # Mapea tu script de datos para que Mongo lo ejecute al iniciar
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      # Guarda los datos de Mongo en un volumen para que no se borren
      - mongo-data:/data/db

volumes:
  mongo-data:


